recipes/accounts/urls.py
from django.urls import path

from accounts.views import UserRegisterView, UserLoginView

urlpatterns = (
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
)

recipes/recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.web.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/recipes/web/urls.py
from django.urls import path

from recipes.web import views
from recipes.web.views import show_index, edit_recipe, delete_recipe, recipe_details, RecipeCreateView

urlpatterns = (
    path('', show_index, name='show index'),
    path('create/', views.RecipeCreateView.as_view(), name='create recipe'),
    path('edit/<int:pk>', edit_recipe, name='edit recipe'),
    path('delete/<int:pk>', delete_recipe, name='delete recipe'),
    path('details/<int:pk>', recipe_details, name='details'),


)

recipes/accounts/models.py
from django.contrib.auth import models as auth_models
from django.db import models

from accounts.managers import RecipesUserManager


class RecipesUser(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    email = models.EmailField(
        unique=True,
        null=False,
        blank=False,
    )

    is_staff = models.BooleanField(
        default=False,
    )

    date_joined = models.DateTimeField(
        auto_now_add=True,
    )

    USERNAME_FIELD = 'email'

    objects = RecipesUserManager()

class Profile(models.Model):
    first_name = models.CharField(
        max_length=25,
    )

    user = models.OneToOneField(
        RecipesUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )

recipes/recipes/web/models.py
from django.db import models
from django.shortcuts import redirect


class Recipe(models.Model):
    TITLE_MAX_LENGTH = 30
    INGREDIENTS_MAX_LENGTH = 250

    title = models.CharField(
        max_length=TITLE_MAX_LENGTH,
    )

    image_url = models.URLField()

    description = models.TextField()

    ingredients = models.CharField(
        max_length=INGREDIENTS_MAX_LENGTH
    )

    time = models.IntegerField()

recipes/recipes/web/forms.py
from django import forms

from recipes.web.models import Recipe
import os


class CreateRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'image_url', 'description', 'ingredients', 'time')
        labels = {
            'title': 'Title',
            'image_url': 'Image URL',
            'description': 'Description',
            'ingredients': 'Ingredients',
            'time': 'Time (Minutes)',
        }


class EditRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'image_url', 'description', 'ingredients', 'time')
        labels = {
            'title': 'Title',
            'image_url': 'Image URL',
            'description': 'Description',
            'ingredients': 'Ingredients',
            'time': 'Time (Minutes)',
        }


class DeleteRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'  # Q&A session- to be confirmed how to do it
            field.required = False

    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    def save(self, commit=True):
        image_path = self.instance.image.path
        self.instance.delete()
        Recipe.objects.all().delete()   # Delete all expenses when deleting the Profile
        os.remove(image_path)
        return self.instance

    class Meta:
        model = Recipe
        fields = ('title', 'image_url', 'description', 'ingredients', 'time')
        labels = {
            'title': 'Title',
            'image_url': 'Image URL',
            'description': 'Description',
            'ingredients': 'Ingredients',
            'time': 'Time (Minutes)',
        }

recipes/accounts/views.py
from django import forms
from django.contrib.auth import forms as auth_forms, login
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views import generic as views
from django.shortcuts import render

from accounts.models import RecipesUser


class UserRegisterForm(auth_forms.UserCreationForm):
    # first_name = forms.CharField(max_length=25)

    class Meta:
        model = RecipesUser
        fields = ('email',)


class UserRegisterView(views.CreateView):
    form_class = UserRegisterForm
    model = RecipesUser
    template_name = 'register.html'
    success_url = reverse_lazy('show index')

    def form_valid(self, form):
        result = super().form_valid(form)
        # user => self.object
        # request => self.request
        login(self.request, self.object)
        return result


class UserLoginView(auth_views.LoginView):
    template_name = 'login.html'

    def get_success_url(self):
        next = self.request.GET.get('next', None)
        if next:
            return next
        return reverse_lazy('show index')

recipes/recipes/web/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from recipes.web.forms import CreateRecipeForm, EditRecipeForm, DeleteRecipeForm
from recipes.web.models import Recipe


def get_recipes():
    recipes = Recipe.objects.all()
    recipes_list = [r.title for r in recipes]
    if len(recipes_list) > 0:
        return True

    return False


def show_index(request):
    recipe = get_recipes()
    recipes = Recipe.objects.all()

    context = {
        'recipe': recipe,
        'recipes': recipes,
    }

    return render(request, 'index.html', context)


# def create_recipe(request):
#     if request.method == 'POST':
#         form = CreateRecipeForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('show index')
#     else:
#         form = CreateRecipeForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'create.html', context)

class RecipeCreateView(CreateView):
    model = Recipe
    template_name = 'create.html'
    success_url = reverse_lazy('show index')
    fields = '__all__'


def edit_recipe(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    if request.method == 'POST':
        form = EditRecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('show index')
    else:
        form = EditRecipeForm(instance=recipe)
    context = {
        'form': form,
        "recipe": recipe,
    }
    return render(request, 'edit.html', context)


def delete_recipe(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    if request.method == 'POST':
        Recipe.delete(recipe)
        return redirect('show index')
    else:
        form = DeleteRecipeForm(instance=recipe)
        context = {
            'form': form,
            "recipe": recipe,
        }
    return render(request, 'delete.html', context)


def recipe_details(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    ingredients = recipe.ingredients
    list_ingredients = ingredients.split(", ")
    context = {
        'recipe': recipe,
        'list_ingredients': list_ingredients,
    }
    return render(request, 'details.html', context)

recipes/templates/base/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Recipes</title>
</head>

<body>

    <nav>
        <ul>
            <img src="{% static 'images/chef.png' %}" alt="chef">
            <li class="title"><a href="/">Recipes</a></li>
            <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
            <li><a href="{% url 'login' %}">Sign In</a></li>
            <li><a href="{% url 'register' %}">Sign Up</a></li>
           
        </ul>
    </nav>
    <div class="container">
        {% block page_content %}
        {% endblock %}
        </div>


</body>

</html>

recipes/templates/create.html
{% extends 'base/base.html' %}
{% block page_content %}
        
<h1>Create Recipe</h1>
<div class="items-container">
    <div class="item">
        <form id="create-form" method="POST" action="{% url 'create recipe' %}">
            {{ form }}
            {% csrf_token %}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" required="" id="id_time">#}
            <input type="submit" value="Create">
        </form>
    </div>
</div>
{% endblock %}

recipes/templates/delete.html
{% extends 'base/base.html' %}
{% block page_content %}
        
<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST" action="{% url 'delete recipe' recipe.pk%}">>
            {{ form }}
            {% csrf_token %}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" disabled="" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200" disabled="" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
{#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250" disabled="" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="30" disabled="" required="" id="id_time">#}
            <input type="submit" class="button delete" value="Delete">
        </form>
    </div>
</div>
{% endblock %}

recipes/templates/details.html
{% extends 'base/base.html' %}
{% block page_content %}
{% load static %}
        
<h1>Recipe Details</h1>
        <div class="items-container">
            <div class="item">
                <h2>{{ recipe.title }}</h2>
                <img class="detail-img" src="{{ recipe.image_url }}" alt="recipe-image">
                <div class="time">
                    <img src="{% static 'images/clock.png' %}">
                    <p>{{ recipe.time }}min</p>
                </div>
                <h3>Ingredients</h3>
                <ul>
                    {% for ingr in list_ingredients %}
                        <li>{{ ingr }}</li>
                    
{#                        <li>4 medium (blank)s carrots halved</li>#}
{#                    #}
{#                        <li>4 stalks celery halved</li>#}
{#                    #}
{#                        <li>1 large onion halved</li>#}
{#                    #}
{#                        <li>water to cover</li>#}
{#                    #}
{#                        <li>salt and pepper to taste</li>#}
{#                    #}
{#                        <li>1 teaspoon chicken bouillon granules</li>#}
                    {% endfor %}
                    
                </ul>
                <h3>How to prepare?</h3>
                <div class="recipe-info-full">
                    {{ recipe.description }}
                </div>
                <div class="buttons-container">
                    <a class="button edit" href="{% url 'edit recipe' recipe.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete recipe' recipe.pk %}">Delete</a>
                </div>
            </div>
        </div>
{% endblock %}

recipes/templates/edit.html
{% extends 'base/base.html' %}
{% block page_content %}
        
<h1>Edit Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST" action="{% url 'edit recipe' recipe.pk%}">
            {{ form }}
            {% csrf_token %}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200"  required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10"  required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
{#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250"  required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="30" required="" id="id_time">#}
            <input type="submit" class="button edit" value="Edit">
        </form>
    </div>
</div>
{% endblock %}

recipes/templates/index.html
{% extends 'base/base.html' %}
{% block page_content %}
    {% if not recipe %}
        <h1>My Recipes</h1>
        <h2>There are no recipes.</h2>
    {% else %}
        {% for r in recipes %}
        <div class="items-container">
            <div class="item">
                <h2>{{ r.title }}</h2>
                 <img class="detail-img" >
                        <img src="{{ r.image_url }}" alt="recipe-image">
                <div class="recipe-info">
                    {{ r.description }}
                </div>
                <div class="buttons-container">
                    <a class="button detail" href="{% url 'details' r.pk %}">Details</a>
                    <a class="button edit" href="{% url 'edit recipe' r.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete recipe' r.pk %}">Delete</a>
                </div>
        {% endfor %}

            </div>
        {% endif %}

        </div>
{% endblock %}

recipes/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<div class="music-img">
<body>
    <section class="createPage">
        <form action="{% url 'login' %}?next={{ next }}" method="post">
{#            <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon">#}
            <fieldset>
                <div class="container">
    {% csrf_token %}
    {{ form }}
    <button>Login</button>
                </div>
            </fieldset>
        </form>
        </section>
</body>
</div>

recipes/templates/register.html
<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Create My Account" id="submit">
</form>